name: 'block_scan'
mysql:
  host: ''
  db: 'aias'
  password: 'aias.yyds'
  user: 'aias'
api: '95bhttps://fragrant-dark-pine.bsc.quiknode.pro/977be32e92f335ddc7095549c7264aeedba23/'
start_block: 25823050

